### PR TITLE
examples: Update `wgpu`

### PR DESCRIPTION
**Pull request by ids1024**

### CODE REVIEW

**Comment by i509VCB** [comment]
It seems that wgpu 0.15 requires rustc 1.63. However it's just a test dependency. Maybe we need to split our CI into testing the crate builds for 1.60 and test the examples in 1.63 or later? @kchibisov winit now has a MSRV if I recall?

Otherwise it looks fine and just needs to have conflicts be resolved.

**Comment by kchibisov** [comment]
We'll bump MSRV to 1.64.0 for the next release.

**Comment by ids1024** [comment]
So, no harm in just updating CI to 1.63 then?

**Comment by kchibisov** [comment]
Yeah, the raw-window-handle will be bumped to 1.64 anyway, so you might bump straight to 1.64 while at it.

**Comment by i509VCB** [comment]
Bump?

**Comment by i509VCB** [comment]
Make sure to update the README and it's all good then.

**Review by i509VCB — APPROVED** [review]

**Pull request merged**
