### PR TITLE
keyboard: fix repeat interval

### PR DESCRIPTION
**Pull request by kchibisov**
The interval is in CHARACTERS per second.

### CODE REVIEW

**Comment by wash2** [comment]
Ok thanks! I see what you mean. Looking at https://wayland.app/protocols/wayland#wl_keyboard:event:repeat_info it seems like it might be possible for the rate to be 0 though? Do you think it would be good to add a check that disables repetition in the case that `rate` is 0?

**Comment by kchibisov** [comment]
The entire logic wrt keyboard repeat should be cleaned imho. The way it's right now suggests that it was not really tested given that part of the code was using ms, and then doing delays in usec.

I'd look more into it once I have time, the thing is that I simply wanted to open a patch in a way that fixed my problem during winit update.

**Comment by wash2** [comment]
> I'd look more into it once I have time, the thing is that I simply wanted to open a patch in a way that fixed my problem during winit update.

I understand that you only want to fix your problem, but I ask to handle the case of 0 because your current fix might end up dividing by zero, which would panic. Do you think you could make an adjustment to disable repetition in the case of 0?

**Comment by kchibisov** [comment]
>I'd look more into it once I have time

**Review by wash2 — APPROVED** [review]
Ok, double checking the type of rate, I can see that it is NonZeroU32 so I'll approve and merge this.

**Pull request merged**
