### PR TITLE
event_loop: remove the WaylandSource

### PR DESCRIPTION
**Pull request by kchibisov**
The `calloop`'s WaylandSource integration is a part of the wayland-client crate.

--

It won't build without `log` until the https://github.com/Smithay/wayland-rs/pull/594

### CODE REVIEW

**Comment by i509VCB** [comment]
This looks good, pending the wayland-rs pull request.

**Comment by kchibisov** [comment]
Hm, given that sctk forces log(it always has it in a dep), shouldn't it be changed to provide it via feature as well?

**Review by i509VCB — APPROVED** [review]
we will need another wayland-rs release in order to remove the todo in the cargo.toml

**Comment by kchibisov** [comment]
Yeah, even a patch release would be nice, given that the build is broken entirely right now and that wasn't noticed.

**Pull request merged**
