### PR TITLE
bump calloop

### PR DESCRIPTION
**Pull request by wizardwatch**

### CODE REVIEW

**Comment by vberger** [comment]
Hi, thanks for this PR!

However this version of calloop introduced some breaking changes that need to be adjusted for before the update can be merged, so I cannot merge this version bump as-is.

**Comment by wizardwatch** [comment]
Could you create an issue with some details about what needs worked on to update calloop? If it’s simple enough I can try to get those changes merged into this pr.

**Comment by vberger** [comment]
I don't have an of-the-top-of-my-head view of what needs to be done (I'm quite occupied by out-of-OSS stuff at the moment) sorry, but the [calloop 0.7 changelog](https://github.com/Smithay/calloop/blob/master/CHANGELOG.md#070----2020-10-13) should give you an idea of what needs to be changed I think.

**Comment by vberger** [comment]
Closing in favor of #189

**Pull request closed without merging**
