### PR TITLE
Fix build error on big-endian targets

### PR DESCRIPTION
**Pull request by io12**
Fixes issue https://github.com/Smithay/client-toolkit/issues/54

### CODE REVIEW

**Comment by dvc94ch** [comment]
Why don't you fix it like the error message suggests by removing the semicolon?

**Comment by io12** [comment]
I figured it would be better for it to be an `if` expression so the compiler can check both branches (to prevent an issue like this from happening again). Also, it's inconsistent to have a return statement on one branch and an implicit return on another.

**Comment by vberger** [comment]
> I figured it would be better for it to be an if expression so the compiler can check both branches (to prevent an issue like this from happening again).

I agree, this `if` will be eliminated by the optimizer anyway, so it's better this way. :+1:

**Comment by vberger** [comment]
Thanks!

**Comment by io12** [comment]
Can a new release be created so this fix is available?

**Comment by vberger** [comment]
v0.4.4 is now released

**Comment by io12** [comment]
Thanks!

**Pull request merged**
