### PR TITLE
Use fully-qualified Result in macro definitions

### PR DESCRIPTION
**Pull request by JasonXJ**

### CODE REVIEW

**Comment by i509VCB** [comment]
I'm guessing some other `Result` import breaks the macro expansion?

**Comment by JasonXJ** [comment]
Yes, I think I have also read somewhere else that it is recommended to use fully qualified in macros.

**Comment by JasonXJ** [comment]
I am not very sure about the CI checks. (I am not familiar with CI in github). It seems that the failures are not relevant to this pull request?

**Comment by i509VCB** [comment]
Yeah the CI failures appear to be outside your pull request

**Review by i509VCB — APPROVED** [review]

**Pull request merged**
